In [4]:
import numpy as np
np_vector = np.array([1, 2, 3])
print(np_vector)
print(type(np_vector))
print(np_vector.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [5]:
np_matrix = np.array([
  [1, 2, 3], 
  [3, 4, 5]
])
print(np_matrix)
print(type(np_matrix))
print(np_matrix.shape)

[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
(2, 3)


In [6]:
np_cube = np.array([
  [[1, 2], [4, 3], [5, 9]],
  [[3, 1], [0, 1], [9, 1]]
])
print(np_cube)
print(type(np_cube))
print(np_cube.shape)

[[[1 2]
  [4 3]
  [5 9]]

 [[3 1]
  [0 1]
  [9 1]]]
<class 'numpy.ndarray'>
(2, 3, 2)


In [11]:
import numpy as np
np_vector = np.full((2, 3, 2), 999)
print(np_vector)

[[[999 999]
  [999 999]
  [999 999]]

 [[999 999]
  [999 999]
  [999 999]]]


In [13]:
import numpy as np
unit_matrix = np.eye((3))
print(unit_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
np_vector = np.arange(1, 22, 4)
print(np_vector)

[ 1  5  9 13 17 21]


In [17]:
rand_matrix = np.random.random((2, 3))
print(rand_matrix)

[[0.55350605 0.86914185 0.62094348]
 [0.42087663 0.37867935 0.77139289]]
