In [0]:
import numpy as np

In [3]:
np_vector = np.random.random((5, ))
print(np_vector)

[0.03061921 0.0652371  0.76596883 0.29752185 0.60742238]


In [4]:
for x in np.nditer(np_vector):
  print(x)

0.030619212103299764
0.06523709861816351
0.7659688303063822
0.29752185062773706
0.6074223759355711


In [5]:
np_matrix = np.random.random((2, 3))
print(np_matrix)

[[0.92926705 0.25273345 0.0932238 ]
 [0.15879433 0.07944283 0.48814254]]


In [6]:
for x in np.nditer(np_matrix):
  print(x)

0.9292670474609291
0.25273345217517473
0.09322379689689841
0.158794331817119
0.07944282776363643
0.4881425417843246


In [7]:
np_cube = np.random.random((2, 3, 2))
print(np_cube)

[[[0.20207333 0.76086473]
  [0.67229568 0.96546349]
  [0.92740768 0.42903065]]

 [[0.55763989 0.33865093]
  [0.91500317 0.86448046]
  [0.46792632 0.4879308 ]]]


In [8]:
for x in np.nditer(np_cube):
  print(x)

0.2020733333648257
0.7608647252947154
0.6722956761965468
0.9654634874473217
0.9274076774002101
0.4290306459568358
0.5576398891510996
0.33865093077082953
0.9150031681508976
0.864480458523368
0.467926319819853
0.48793079829719466


In [9]:
np_matrix = np.random.random((3, 4))
print(np_matrix)

[[0.17979289 0.24329813 0.60849771 0.48733693]
 [0.89634821 0.50599983 0.56840653 0.24567629]
 [0.98674902 0.78402406 0.69839247 0.20729408]]


In [12]:
for x in np.nditer(np_matrix, flags = ['external_loop'], order = 'F'):
  print(x)

[0.17979289 0.89634821 0.98674902]
[0.24329813 0.50599983 0.78402406]
[0.60849771 0.56840653 0.69839247]
[0.48733693 0.24567629 0.20729408]


In [0]:
for x in np.nditer(np_matrix, flags = ['external_loop', order = 'C']):
  print