In [3]:
import numpy as np
a = np.array([
  [1, 2, 3, 4],
  [3, 4, 5, 6]
])
print(a)
print(a.shape)

[[1 2 3 4]
 [3 4 5 6]]
(2, 4)


In [4]:
b = a.reshape(4, 2)
print(b)
print(b.shape)

[[1 2]
 [3 4]
 [3 4]
 [5 6]]
(4, 2)


In [5]:
c = a.reshape(2, 2, 2)
print(c)
print(c.shape)

[[[1 2]
  [3 4]]

 [[3 4]
  [5 6]]]
(2, 2, 2)


In [6]:
a = np.random.random((2, 2, 2))
print(a)
print(a.shape)

[[[0.12574317 0.45526065]
  [0.4947265  0.86976331]]

 [[0.97443659 0.70407823]
  [0.54639367 0.57424435]]]
(2, 2, 2)


In [7]:
b = a.flatten()
print(b)
print(b.shape)

[0.12574317 0.45526065 0.4947265  0.86976331 0.97443659 0.70407823
 0.54639367 0.57424435]
(8,)


In [8]:
a = np.random.random((2, 2))
print(a)
print(a.shape)

[[0.35286937 0.93640312]
 [0.88722966 0.62775563]]
(2, 2)


In [11]:
b = np.expand_dims(a, axis = 2)
print(b)
print(b.shape)

[[[0.35286937]
  [0.93640312]]

 [[0.88722966]
  [0.62775563]]]
(2, 2, 1)


In [12]:
a = np.random.random((1, 2, 2, 1))
print(a)
print(a.shape)

[[[[0.26039419]
   [0.50069155]]

  [[0.45429666]
   [0.03866973]]]]
(1, 2, 2, 1)


In [13]:
b = np.squeeze(a, axis = 0)
print(b)
print(b.shape)

[[[0.26039419]
  [0.50069155]]

 [[0.45429666]
  [0.03866973]]]
(2, 2, 1)


In [14]:
a = np.random.random((2, 3))
print(a)
print(a.shape)

[[0.7280401  0.31074818 0.70802009]
 [0.7202142  0.10260045 0.61692746]]
(2, 3)


In [15]:
b = a.T
print(b)
print(b.shape)

[[0.7280401  0.7202142 ]
 [0.31074818 0.10260045]
 [0.70802009 0.61692746]]
(3, 2)


In [16]:
c = np.transpose(a)
print(c)
print(c.shape)

[[0.7280401  0.7202142 ]
 [0.31074818 0.10260045]
 [0.70802009 0.61692746]]
(3, 2)
