In [4]:
import numpy as np
np_vector = np.array([1, 2, 3, 4])
print(np_vector)
np_vector = np_vector + 3
print(np_vector)
np_vector = np_vector + np.array([3, 3, 3, 3])
print(np_vector)
np_vector = np_vector - 3
print(np_vector)

[1 2 3 4]
[4 5 6 7]
[ 7  8  9 10]
[4 5 6 7]


In [6]:
np_matrix = np.array([
  [1, 2,3],
  [4, 3, 1]
])
print(np_matrix)
np_matrix = np_matrix * 2
print(np_matrix)

[[1 2 3]
 [4 3 1]]
[[2 4 6]
 [8 6 2]]


In [0]:
np_vector = np.arange(0, 22, 3)
print()