In [0]:
import pandas as pd
import numpy as np

In [3]:
S = pd.Series(np.random.randint(100, size = 5))
print(S)
print(type(S))

0    82
1     3
2    13
3     1
4    53
dtype: int64
<class 'pandas.core.series.Series'>


In [4]:
print(S.index)

RangeIndex(start=0, stop=5, step=1)


In [5]:
print(S.values)

[82  3 13  1 53]


In [6]:
chiso = ['kien truc', 'cntt', 'dulich', 'xay dung']
giatri = [123, 435, 321, 871]
S = pd.Series(giatri, index = chiso)
print(S)

kien truc    123
cntt         435
dulich       321
xay dung     871
dtype: int64


In [7]:
print(S.index)

Index(['kien truc', 'cntt', 'dulich', 'xay dung'], dtype='object')


In [8]:
print(S.values)

[123 435 321 871]


In [12]:
dic = {
    'a': [1, 2, 3, 4, 5],
    'b': [1.3, 3.4, 4.5, 5.8, 9],
    'c': ['v1', 'v3', 'v2', 'v5', 'v8']
}
df = pd.DataFrame(dic)
print(df)
print(type(df))
print(df.info())

   a    b   c
0  1  1.3  v1
1  2  3.4  v3
2  3  4.5  v2
3  4  5.8  v5
4  5  9.0  v8
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       5 non-null      int64  
 1   b       5 non-null      float64
 2   c       5 non-null      object 
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes
None


In [13]:
print(df.head(2))

   a    b   c
0  1  1.3  v1
1  2  3.4  v3


In [14]:
print(df.tail(3))

   a    b   c
2  3  4.5  v2
3  4  5.8  v5
4  5  9.0  v8


In [15]:
print(df.columns.values)

['a' 'b' 'c']


In [16]:
print(df.index.values)

[0 1 2 3 4]


In [17]:
print(df.shape)

(5, 3)
