In [0]:
import numpy as np

In [3]:
np_matrix = np.array([
  [1, 2, 3],
  [4, 9, 0]
])
print(np_matrix)
print(np_matrix.shape)

[[1 2 3]
 [4 9 0]]
(2, 3)


In [4]:
print(np_matrix[0,:2])

[1 2]


In [5]:
print(np_matrix[:, 0])

[1 4]


In [6]:
print(np_matrix[-1])

[4 9 0]


In [9]:
print(np_matrix[-1, :2])
print(np_matrix[-1, :2].shape)

[4 9]
(2,)


In [10]:
print(np_matrix[:1, :2])
print(np_matrix[:1, :2].shape)

[[1 2]]
(1, 2)


In [0]:
import numpy as np
np_matrix = np.random.random((4, 6))

In [12]:
print(np_matrix)

[[0.57195592 0.56329513 0.2949257  0.30970437 0.70655067 0.8536009 ]
 [0.95794952 0.68839148 0.27822409 0.84175418 0.77159733 0.9438838 ]
 [0.77666503 0.0090992  0.43759519 0.86940639 0.24841401 0.84474313]
 [0.42261856 0.05304039 0.06279922 0.51947047 0.3288742  0.53457505]]


In [20]:
print(np_matrix[0:1])
print(np_matrix[0:1].shape)
print(np_matrix[0:1][-1])
print(np_matrix[0:1][-1].shape)
print(np_matrix[0:1][-1][1:3])
print(np_matrix[0:1][-1][3:])

[[0.57195592 0.56329513 0.2949257  0.30970437 0.70655067 0.8536009 ]]
(1, 6)
[0.57195592 0.56329513 0.2949257  0.30970437 0.70655067 0.8536009 ]
(6,)
[0.56329513 0.2949257 ]
[0.30970437 0.70655067 0.8536009 ]
