In [0]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print(a)
print(b)
print(a.shape)
print(b.shape)

[1 2 3 4]
[3 4 5 6]
(4,)
(4,)


In [4]:
print(a * b)
print(np.inner(a, b))

[ 3  8 15 24]
50


In [5]:
a = np.array([
  [1, 2, 3],
  [3, 4, 5]
])
b = np.array([
  [3, 4, 5],
  [1, 2, 0],
  [3, 4, 1]
])
print(a)
print(a.shape)
print(b)
print(b.shape)

[[1 2 3]
 [3 4 5]]
(2, 3)
[[3 4 5]
 [1 2 0]
 [3 4 1]]
(3, 3)


In [6]:
c = a.dot(b)
print(c)
print(c.shape)

[[14 20  8]
 [28 40 20]]
(2, 3)


In [7]:
a = np.array([
  [1, 2],
  [3, 3]
])
b = np.array([
  [3, 4],
  [1, 9]
])
print(a)
print(a.shape)
print(b)
print(b.shape)

[[1 2]
 [3 3]]
(2, 2)
[[3 4]
 [1 9]]
(2, 2)


In [8]:
print(np.tensordot(a, b))

41


In [10]:
from numpy import linalg
a = np.array([1, 2, 3])
print(a)
print(linalg.norm(a)) #l2 norm

[1 2 3]
3.7416573867739413


In [11]:
a = np.array([1, 2, -3])
print(a)
print(linalg.norm(a, ord = 1)) #l1 norm

[ 1  2 -3]
6.0


In [14]:
a = np.array([
  [1, 2, 3],
  [3, 4, -1]
])
b = np.array([
  [3, 4, 5],
  [1, 2, 9]
])
print(np.subtract(a,b))

[[ -2  -2  -2]
 [  2   2 -10]]
