In [0]:
import numpy as np


In [5]:
np_vector = np.array([1, 2, 3, 4])
print(np_vector)
#np_vector = np_vector + 3
np_vector = np_vector - 3 #np.array([3, 3, 3, 3])
print(np_vector)

[1 2 3 4]
[-2 -1  0  1]


In [7]:
np_matrix = np.array([
  [1, 2, 3],
  [4, 5, 8]
])
print(np_matrix)
np_matrix = np_matrix * 2
print(np_matrix)

[[1 2 3]
 [4 5 8]]
[[ 2  4  6]
 [ 8 10 16]]


In [9]:
np_vector = np.arange(0, 20, 3)
print(np_vector)
np_vector *= 3
print(np_vector)

[ 0  3  6  9 12 15 18]
[ 0  9 18 27 36 45 54]


In [11]:
np_matrix = np.ones((3, 5))
print(np_matrix)
np_matrix *= 2
print(np_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [12]:
a = np.ones((3, 5))
b = np.arange(5)
print(a)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 1 2 3 4]


In [13]:
c = a + b
print(c)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [14]:
print(c.shape)

(3, 5)


In [15]:
a = np.arange(5).reshape(5, 1)
print(a)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [16]:
print(a.shape)

(5, 1)


In [18]:
b = np.arange(5)
print(b)
print(b.shape)

[0 1 2 3 4]
(5,)


In [19]:
c = a + b
print(c)
print(c.shape)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
(5, 5)


In [23]:
a = np.array([
  [1, 2, 3],
  [3, 3, 4]
])
b = np.arange(3)
print(a)
print(b)
print(a.shape)
print(b.shape)
c = a + b
print(c)
print(c.shape)

[[1 2 3]
 [3 3 4]]
[0 1 2]
(2, 3)
(3,)
[[1 3 5]
 [3 4 6]]
(2, 3)


In [24]:
a = np.array([
  [1, 2, 3],
  [2, 3, 4]
])
b = np.array([
  [2],
  [4]
])
print(a)
print(b)


[[1 2 3]
 [2 3 4]]
[[2]
 [4]]


In [25]:
print(a.shape)
print(b.shape)

(2, 3)
(2, 1)


In [26]:
c = a + b
print(c)
print(c.shape)

[[3 4 5]
 [6 7 8]]
(2, 3)
